[workspace]
members = ["day01"]
resolver = "2"

[workspace.dependencies]
miette = { version = "5.10", features = ["fancy"] }
thiserror = "1.0.50"
phf = { version = "0.11.2",  features = ["macros"] }
rstest = "0.18.2"
